apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-preview-stakater-nordmart-review
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: preview
    stakater.com/kind: preview      
spec:
  destination:
    namespace: gabbar-preview
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: 01-gabbar/01-stakater-nordmart-review/00-preview
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
