pipeline-charts:
  name: veeru-ci
  workspaces:
    - name: source
      volumeClaimTemplate:
        accessModes: ReadWriteOnce
        resourcesRequestsStorage: 1Gi
  pipelines:
    finally:
      - taskName: stakater-set-commit-status-v1
        name: set-commit-status-task-result
      - taskName: stakater-notify-slack-v1
        name: notify-slack
        params:
        - name: namespace
        - name: author
        - name: gitrevision
        - name: repo
          value: $(params.repoName)
        - name: gitrepositoryurl
        - name: tekton-base-url
        - name: prnumber
    tasks:
      - taskName: stakater-set-commit-status-v1
        params:
        - name: state
          value: pending
      - taskName: git-clone
      - taskName: stakater-create-git-tag-v1
        params:
          - name: oldcommit
          - name: action
      - taskName: stakater-code-linting-v1
      - taskName: stakater-kube-linting-v1
        params:
        - name: namespace
          value: $(context.pipelineRun.namespace)
        runAfter:
        - stakater-create-git-tag-v1
      - taskName: stakater-unit-test-v1
        runAfter:
        - stakater-kube-linting-v1
        - stakater-code-linting-v1
      - taskName: stakater-sonarqube-scanner-v1
        runAfter:
          - stakater-unit-test-v1
      - taskName: stakater-build-image-flag-v1
        runAfter:
        - stakater-unit-test-v1
        workspaces:
          - name: source
            workspace: source
        params:
          - name: oldcommit
          - name: newcommit
      - taskName: stakater-buildah-v1
        name: build-and-push
        runAfter:
          - stakater-build-image-flag-v1
        params:
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        - name: IMAGE_REGISTRY
          value: $(params.image_registry_url)
        - name: CURRENT_GIT_TAG
          value: $(tasks.stakater-create-git-tag-v1.results.CURRENT_GIT_TAG)
      - taskName: stakater-trivy-scan-v1
        params:
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-image-scan
        params:
        - name: image_digest
          value: $(tasks.build-and-push.results.IMAGE_DIGEST)
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-image-check
        params:
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-deployment-check
        params:
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: stakater-checkov-scan-v1
        params:
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: stakater-comment-on-github-pr-v1
        runAfter:
        - stakater-trivy-scan-v1
        - rox-image-scan
        - rox-image-check
        - rox-deployment-check
        - stakater-checkov-scan-v1
      - taskName: stakater-helm-push-v1
      - taskName: stakater-create-environment-v1
      - taskName: stakater-update-cd-repo-v3
      - taskName: stakater-push-main-tag-v1
      - taskName: stakater-app-sync-and-wait-v1
        params:
        - name: timeout
          value: "120"
  triggertemplate:
    serviceAccountName: stakater-tekton-builder
    pipelineRunNamePrefix: $(tt.params.repoName)-$(tt.params.prnumberBranch)
  eventlistener:
    serviceAccountName: stakater-tekton-builder
    triggers:
    - name: stakater-pr-cleaner-v2-pullrequest-merge
      create: false
    - name: pullrequest-create
      create: true
      bindings:
      - ref: stakater-pr-v1
      - name: oldcommit
        value: $(body.pull_request.base.sha)
      - name: newcommit
        value: $(body.pull_request.head.sha)
    - name: pullrequest-synchronize
      create: true
      bindings:
        - ref: stakater-pr-v1
        - name: oldcommit
          value: $(body.before)
        - name: newcommit
          value: $(body.after)
    - name: push
      create: true
      bindings:
        - ref: stakater-main-v1
        - name: oldcommit
          value: $(body.before)
        - name: newcommit
          value: $(body.after)
  rbac:
    enabled: false
  serviceAccount:
    name: stakater-tekton-builder
    create: false
