apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-402-stakater-nordmart-review-14505977
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: arsenal
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: update-chart
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-update-chart
          version: '*'
      interval: 1m0s
      releaseName: update-chart
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-402-1eafc773
