apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  annotations:
    stakater.com/repo-name: stakater-nordmart-review
  name: pr-409-stakater-nordmart-review-51ac6908
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: arsenal
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: renovate/registry.access.redhat.com-ubi8-openjdk-11-1.14.x
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-renovate/registry.access.redhat.com-ubi8-openjdk-
          version: '*'
      interval: 1m0s
      releaseName: renovate/registry.access.redhat.com-ubi8-openjdk-
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-409-51ac6908
