apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-review-pr-xx
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-review
        ref: add-tronador-yaml
        path: deploy/
      releaseName: add-tronador-yaml
      values:
        application:
          deployment:
            image:
              tag: v0.0.2

