apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build-pipelines
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: build
    stakater.com/kind: build    
spec:
  destination:
    namespace: gabbar-build
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: 01-gabbar/03-pipelines/00-build
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
