apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psg-preview-stakater-nordmart-review-api
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: psg
    stakater.com/env: preview
    stakater.com/kind: preview      
spec:
  destination:
    namespace: psg-preview
    server: 'https://kubernetes.default.svc'
  project: psg
  source:
    path: 03-psg/01-stakater-nordmart-review-api/00-preview
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
