apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-preview-stakater-nordmart-review-ui
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: preview
    stakater.com/kind: preview    
spec:
  destination:
    namespace: arsenal-preview
    server: 'https://kubernetes.default.svc'
  project: arsenal
  source:
    path: 01-arsenal/02-stakater-nordmart-review-ui/00-preview
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
