apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-build
  namespace: openshift-gitops
spec:
  destination:
    namespace: veeru-build
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/00-argocd-apps/00-build/
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
    directory:
      recurse: true
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
