apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: veeru
spec:
  quota: medium
  owners:
    users:
      - bilal.bokharee@stakater.com
      # Test user for Stakater Cloud IAM
      - sro-privileged
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/gitops-config-template'
      - 'https://nexus-helm-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/repository/helm-charts/'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - build
  - preview
  - dev
  - stage
  - prod
