stakater-nordmart-review-ui:
  application:
    applicationName: "review-ui-green"
    deployment:
      imagePullSecrets: []
      additionalLabels:
        blue_green: inactive
      image:
        repository: stakater/stakater-nordmart-review-ui
        tag: 1.0.15-green
    service:
      additionalLabels:
        blue_green: active
    route:
      enabled: false
