apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-allure
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: dev
    stakater.com/kind: dev         
spec:
  destination:
    namespace: arsenal-dev
    server: 'https://kubernetes.default.svc'
  project: arsenal 
  source:
    path: stakater/allure
    repoURL: 'https://github.com/stakater/charts.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
