apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psg-dev-stakater-nordmart-review-ui
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: psg
    stakater.com/env: dev
    stakater.com/kind: dev            
spec:
  destination:
    namespace: psg-dev
    server: 'https://kubernetes.default.svc'
  project: psg
  source:
    path: 03-psg/02-stakater-nordmart-review-ui/01-dev
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
