kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: review-web
spec:
  host: review-web-gabbar-dev.apps.devtest.vxdqgl7u.kubeapp.cloud
  to:
    kind: Service
    name: review-web
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
