apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: git-stakater-nordmart-review-api-git
spec:
  git_provider:
    secret:
      key: provider.token
      name: scm-webhook-creds
    webhook_secret:
      key: webhook.secret
      name: scm-webhook-creds
  url: 'https://github.com/AsfaMumtaz/stakater-nordmart-review-api'
