apiVersion: v2
dependencies:
  - name: pipeline-charts
    repository: https://stakater.github.io/stakater-charts
    version: 0.0.27
description: A Helm chart for Kubernetes
name: stakater-nordmart-review-ui-pipeline
version: 0.0.27
