apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-matomo
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: dev
    stakater.com/kind: dev         
spec:
  destination:
    namespace: gabbar-dev
    server: 'https://kubernetes.default.svc'
  project: gabbar 
  source:
    path: stakater/matomo
    repoURL: 'https://github.com/stakater/charts.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
