apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psg-dev
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  source:
    path: 03-psg/00-argocd-apps/01-dev/
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
    directory:
       recurse: true
  project: psg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
