apiVersion: v2
dependencies:
  - name: stakater-tekton-chart
    repository: https://stakater.github.io/stakater-charts
    version: 2.0.2
description: Helm chart for Tekton Pipelines
name: stakater-main-pr-v2
version: 2.0.2
