apiVersion: v1
kind: Namespace
metadata:
  annotations: null
  labels:
    app: review-web
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    kind: pr
    provider: stakater
    release: stakater-nordmart-review-ui
    stakater.com/tenant: gabbar
    team: gabbar
  name: gabbar-stakater-nordmart-review-ui-pr-14
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: review-web
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review-ui
    team: stakater
  name: review-web
  namespace: gabbar-stakater-nordmart-review-ui-pr-14
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: review-web
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review-ui
    team: stakater
  name: review-web
  namespace: gabbar-stakater-nordmart-review-ui-pr-14
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 4200
  selector:
    app: review-web
    maistra.io/expose-route: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: review-web
    appCategory: frontend
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review-ui
    team: stakater
  name: review-web
  namespace: gabbar-stakater-nordmart-review-ui-pr-14
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: review-web
        maistra.io/expose-route: "true"
    spec:
      containers:
      - env:
        - name: PORT
          value: "4200"
        - name: REVIEW_API
          value: https://review-gabbar-dev.apps.binero-test.8sdzwd1l.kubeapp.cloud
        image: nexus-docker-openshift-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review-ui:SNAPSHOT-PR-14-897967a2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: review-web
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.1
            memory: 128Mi
      imagePullSecrets:
      - name: nexus-docker-config-forked
      serviceAccountName: review-web
---
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  labels:
    app: review-web
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review-ui
    team: stakater
  name: review-web
  namespace: gabbar-stakater-nordmart-review-ui-pr-14
spec:
  group: Nordmart
  icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/stakater-big.png
  name: Review Web
  networkRestricted: false
  urlFrom:
    routeRef:
      name: review-web
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: review-web
    appVersion: SNAPSHOT-PR-14-897967a2
    chart: application-0.0.75
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review-ui
    router: default
    team: stakater
  name: review-web
  namespace: gabbar-stakater-nordmart-review-ui-pr-14
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: review-web
    weight: 100
  wildcardPolicy: None
