apiVersion: tenantoperator.stakater.com/v1beta1
kind: Quota
metadata:
  name: medium
  annotations:
    quota.tenantoperator.stakater.com/is-default: "false"
spec:
  resourcequota:
    hard:
      requests.cpu: "5"
      requests.memory: 8Gi
  limitrange:
    limits:
      - defaultRequest:
          cpu: 200m
          memory: 200Mi
        type: Container
