apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-reg-creds
spec:
  secretStoreRef:
    name: tenant-vault-secret-store
    kind: SecretStore
  refreshInterval: "1m0s"
  target:
    name: docker-reg-creds
    creationPolicy: 'Owner'
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
          conversionStrategy: Default
          key: docker-reg-creds