
stakater-nordmart-review:

  application: 

    deployment:   
      image:
        repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
        tag: 1.0.13
      imagePullSecrets: nexus-docker-config-forked

    externalSecret:
      enabled: true

      secretStore:
        name: tenant-vault-secret-store

      refreshInterval: "1m"
      files:
        # The full name of secret will be review-mongodb-creds; review is applicationName defined above
        mongodb-creds:
          # Data defines the connection between the Kubernetes Secret keys and the Provider data
          data:
              mongodb-root-password:
                remoteRef:
                  key: review-api/prod/mongodb-creds
                  property: mongodb-root-password
